# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba046812422cf65eaf3af438ff94de98105142614ccc26a26e1129fd1f3afb830402413a66e481c562c02e29718f3ac8067eb14eb1ed86b4520749a6200220a7

test:
  secret_key_base: 40cd467b622c6d53c5bdbc5a2ce8874692fb079984191399c183dbd9239482a530dce3b82537f10bad3df15d57fb2faa0894eb16f0149565decbd3d085349b68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
